version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  errordashboard:
   build:
    context: ./
    dockerfile: ./Dockerfile.ErrorDashboard
   ports:
    - "86:80"
   depends_on:
    - rabbitmq
  
  shipping:
   build:
    context: ./
    dockerfile: ./Dockerfile.Shipping
   ports:
    - "85:80"
   depends_on:
    - rabbitmq

  accounting:
    build:
     context: ./
     dockerfile: ./Dockerfile.Accounting
    ports:
      - "84:80"
    depends_on:
      - rabbitmq

  contact:
    build:
     context: ./
     dockerfile: ./Dockerfile.Contact
    ports:
      - "83:80"
    depends_on:
      - rabbitmq

  marketing:
    build:
     context: ./
     dockerfile: ./Dockerfile.Marketing
    ports:
      - "82:80"
    depends_on:
      - rabbitmq

  sales:
    build:
     context: ./
     dockerfile: ./Dockerfile.Sales
    ports:
      - "81:80"
    depends_on:
      - rabbitmq

  warehouse:
    build:
     context: ./
     dockerfile: ./Dockerfile.Warehouse
    ports:
      - "80:80"
    depends_on:
      - rabbitmq

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node

  kibana:
   image: docker.elastic.co/kibana/kibana:7.16.1
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200

volumes:
  elasticsearch-data:
