version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  shipping:
   image: shippingimage
   ports:
    - "85:80"
   depends_on:
    - rabbitmq

  accounting:
    image: accountingimage
    ports:
      - "84:80"
    depends_on:
      - rabbitmq

  contact:
    image: contactimage
    ports:
      - "83:80"
    depends_on:
      - rabbitmq

  marketing:
    image: marketingimage
    ports:
      - "82:80"
    depends_on:
      - rabbitmq

  sales:
    image: salesimage
    ports:
      - "81:80"
    depends_on:
      - rabbitmq

  warehouse:
    image: warehouseimage
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
